/**
 * Sistema de plantillas para el constructor de páginas
 * Plantillas basadas exactamente en los diseños visuales de las imágenes proporcionadas
 */

// ============================================================================
// PLANTILLA 1: HOMEPAGE V2 COMPLETA
// Basada en la imagen del Homepage V2 con todas las secciones
// ============================================================================
export const homepageTemplate = {
  id: 'homepage-v2',
  name: 'Homepage V2 (Completa)',
  description: 'Página de inicio completa: Hero, Noticias Recientes, Conoce sobre, Fotografía Destacada y CTA Foro',
  category: 'Homepage',
  preview: '/templates/homepage-v2-preview.png',
  template: {
    ROOT: {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: true,
      props: { padding: 0, background: '#000000' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['header-navbar', 'hero-forest', 'noticias-section', 'conoce-sobre-section', 'fotografia-destacada-section', 'foro-cta-section'],
      linkedNodes: {},
    },
    // Header/Navbar
    'header-navbar': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 16, margin: 0, layout: 'flex', direction: 'row', justify: 'space-between', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['logo-akaru', 'nav-links'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'logo-akaru': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'A Akaru', fontSize: 24, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'header-navbar',
    },
    'nav-links': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Foro | Tribus | Fauna | Flora | Usos | Agua | Cultura | Geografía', fontSize: 14, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'header-navbar',
    },
    // Hero Section - Imagen de selva
    'hero-forest': {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: false,
      props: { padding: 0, background: '#000000', backgroundImage: '', minHeight: 500, layout: 'flex', direction: 'column', justify: 'center', align: 'center' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
    // Sección Noticias Recientes
    'noticias-section': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 32 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['noticias-title', 'noticias-grid-3col'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'noticias-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Noticias Recientes', fontSize: 32, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'noticias-section',
    },
    'noticias-grid-3col': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'grid', gridColumns: 3, gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'noticias-section',
    },
    // Sección "Conoce sobre"
    'conoce-sobre-section': {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: false,
      props: { padding: 80, background: '#000000', backgroundImage: '', minHeight: 600, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'center', gap: 40 },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['conoce-title', 'conoce-grid-categories'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'conoce-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Conoce sobre', fontSize: 56, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'conoce-sobre-section',
    },
    'conoce-grid-categories': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'grid', gridColumns: 3, gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'conoce-sobre-section',
    },
    // Sección Fotografía Destacada
    'fotografia-destacada-section': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['foto-title', 'foto-image', 'foto-caption'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'foto-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Fotografía Destacada', fontSize: 32, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'fotografia-destacada-section',
    },
    'foto-image': {
      type: { resolvedName: 'Image' },
      isCanvas: false,
      props: { src: '', alt: 'Fotografía destacada', width: '100%', height: 'auto' },
      displayName: 'Image',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'fotografia-destacada-section',
    },
    'foto-caption': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Descripción de la fotografía destacada', fontSize: 16, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'fotografia-destacada-section',
    },
    // Sección CTA Foro
    'foro-cta-section': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'flex', direction: 'row', justify: 'space-between', align: 'center', gap: 32 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['foro-text-block', 'foro-button-cta'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'foro-text-block': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 16 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['foro-cta-title', 'foro-cta-description'],
      linkedNodes: {},
      parent: 'foro-cta-section',
    },
    'foro-cta-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Visita el foro', fontSize: 28, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'foro-text-block',
    },
    'foro-cta-description': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Un espacio diseñado para conectar, aprender y compartir experiencias. ¡Te estamos esperando!', fontSize: 16, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'foro-text-block',
    },
    'foro-button-cta': {
      type: { resolvedName: 'Button' },
      isCanvas: false,
      props: { text: 'Entrar ahora', size: 'large', variant: 'contained', buttonBgColor: '#FF6B35', buttonTextColor: '#ffffff', actionType: 'route', to: '/foro' },
      displayName: 'Button',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'foro-cta-section',
    },
  },
};

// ============================================================================
// PLANTILLA 2: BLOG POST INDIVIDUAL
// Basada en la imagen del post de blog con sidebar de interacción
// ============================================================================
export const blogPostTemplate = {
  id: 'blog-post',
  name: 'Blog Post Individual',
  description: 'Artículo de blog con categoría, título, imagen destacada, contenido y elementos de interacción',
  category: 'Blog',
  preview: '/templates/blog-post-preview.png',
  template: {
    ROOT: {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: true,
      props: { padding: 0, background: '#000000' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['blog-header-nav', 'blog-content-wrapper'],
      linkedNodes: {},
    },
    // Header con breadcrumb
    'blog-header-nav': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#1a1a1a', padding: 12, margin: 0, layout: 'flex', direction: 'row', justify: 'flex-start', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['blog-breadcrumb'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'blog-breadcrumb': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Tribus indigenas / Organizacion Social', fontSize: 12, color: '#999999' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'blog-header-nav',
    },
    // Contenedor principal con sidebar y contenido
    'blog-content-wrapper': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 0, margin: 0, layout: 'flex', direction: 'row', justify: 'flex-start', align: 'flex-start', gap: 0 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['blog-sidebar-interactions', 'blog-main-content'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    // Sidebar de interacciones (izquierda)
    'blog-sidebar-interactions': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 24, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'center', gap: 24, width: 80 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'blog-content-wrapper',
    },
    // Contenido principal del blog
    'blog-main-content': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 48, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['blog-category-tag', 'blog-post-title', 'blog-featured-image', 'blog-post-content'],
      linkedNodes: {},
      parent: 'blog-content-wrapper',
    },
    'blog-category-tag': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#FF6B35', padding: 8, margin: 0, borderRadius: 4 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['blog-category-text'],
      linkedNodes: {},
      parent: 'blog-main-content',
    },
    'blog-category-text': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Fauna', fontSize: 14, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'blog-category-tag',
    },
    'blog-post-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Nueva rana amazónica nombrada en honor a un monstruo mítico', fontSize: 42, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'blog-main-content',
    },
    'blog-featured-image': {
      type: { resolvedName: 'Image' },
      isCanvas: false,
      props: { src: '', alt: 'Imagen destacada del artículo', width: '100%', height: 'auto' },
      displayName: 'Image',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'blog-main-content',
    },
    'blog-post-content': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Contenido completo del artículo. Aquí puedes agregar el texto del blog post que describa el tema en detalle...', fontSize: 16, color: '#ffffff', fontWeight: 'normal' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'blog-main-content',
    },
  },
};

// ============================================================================
// PLANTILLA 3: PÁGINA DE CATEGORÍA (Fauna/Flora/Tribus)
// Basada en las imágenes de páginas de categoría con hero y grid
// ============================================================================
export const categoryPageTemplate = {
  id: 'category-page',
  name: 'Página de Categoría',
  description: 'Página de categoría con hero section grande y grid de artículos relacionados (Fauna, Flora, Tribus, etc.)',
  category: 'Categoría',
  preview: '/templates/category-page-preview.png',
  template: {
    ROOT: {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: true,
      props: { padding: 0, background: '#000000' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['category-header', 'category-hero-banner', 'category-articles-grid'],
      linkedNodes: {},
    },
    'category-header': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 12, margin: 0, layout: 'flex', direction: 'row', justify: 'flex-start', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['category-breadcrumb'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'category-breadcrumb': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Fauna', fontSize: 14, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'category-header',
    },
    'category-hero-banner': {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: false,
      props: { padding: 120, background: '#000000', backgroundImage: '', minHeight: 500, layout: 'flex', direction: 'row', justify: 'flex-start', align: 'center' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['category-hero-title'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'category-hero-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Fauna', fontSize: 72, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'category-hero-banner',
    },
    'category-articles-grid': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'grid', gridColumns: 3, gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'ROOT',
    },
  },
};

// ============================================================================
// PLANTILLA 4: PÁGINA DE FORO
// Basada en la imagen del foro con lista de temas
// ============================================================================
export const forumPageTemplate = {
  id: 'forum-page',
  name: 'Página de Foro',
  description: 'Página de foro con título, botón "Nuevo tema" y lista de temas del foro',
  category: 'Foro',
  preview: '/templates/forum-page-preview.png',
  template: {
    ROOT: {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: true,
      props: { padding: 0, background: '#000000' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['forum-header', 'forum-main-content'],
      linkedNodes: {},
    },
    'forum-header': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#1a1a1a', padding: 16, margin: 0, layout: 'flex', direction: 'row', justify: 'space-between', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['forum-header-breadcrumb'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'forum-header-breadcrumb': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'foro Home', fontSize: 12, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forum-header',
    },
    'forum-main-content': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['forum-title', 'forum-subtitle', 'forum-new-topic-btn', 'forum-topics-list'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'forum-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Foros', fontSize: 48, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forum-main-content',
    },
    'forum-subtitle': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Temas', fontSize: 18, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forum-main-content',
    },
    'forum-new-topic-btn': {
      type: { resolvedName: 'Button' },
      isCanvas: false,
      props: { text: 'Nuevo tema', size: 'medium', variant: 'contained', buttonBgColor: '#FF6B35', buttonTextColor: '#ffffff' },
      displayName: 'Button',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forum-main-content',
    },
    'forum-topics-list': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'stretch', gap: 16 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forum-main-content',
    },
  },
};

// ============================================================================
// PLANTILLA 5: ARTÍCULO DETALLADO
// Basada en la imagen del artículo largo con múltiples secciones
// ============================================================================
export const detailedArticleTemplate = {
  id: 'detailed-article',
  name: 'Artículo Detallado',
  description: 'Artículo largo con múltiples secciones, imágenes intercaladas y texto estructurado',
  category: 'Artículo',
  preview: '/templates/detailed-article-preview.png',
  template: {
    ROOT: {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: true,
      props: { padding: 0, background: '#000000' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['article-header', 'article-content-sections'],
      linkedNodes: {},
    },
    'article-header': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#1a1a1a', padding: 12, margin: 0, layout: 'flex', direction: 'row', justify: 'flex-start', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['article-breadcrumb'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'article-breadcrumb': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Tribus indigenas / Organizacion Social', fontSize: 12, color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-header',
    },
    'article-content-sections': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 40 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['article-category-tag', 'article-main-title', 'article-section-1', 'article-section-2', 'article-section-3'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'article-category-tag': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#FF6B35', padding: 8, margin: 0, borderRadius: 4 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['article-category-text'],
      linkedNodes: {},
      parent: 'article-content-sections',
    },
    'article-category-text': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Tribus Indigenas', fontSize: 14, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-category-tag',
    },
    'article-main-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Organizacion social de las tribus indigenas de la amazonia', fontSize: 40, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-content-sections',
    },
    // Sección 1: Imagen + Texto
    'article-section-1': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['article-img-1', 'article-text-1'],
      linkedNodes: {},
      parent: 'article-content-sections',
    },
    'article-img-1': {
      type: { resolvedName: 'Image' },
      isCanvas: false,
      props: { src: '', alt: 'Primera imagen del artículo', width: '100%', height: 'auto' },
      displayName: 'Image',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-1',
    },
    'article-text-1': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Primera sección de contenido. Las tribus indígenas de la Amazonia tienen una organización social horizontal y egalitaria...', fontSize: 16, color: '#ffffff', fontWeight: 'normal' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-1',
    },
    // Sección 2: Subtítulo + Texto
    'article-section-2': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 16 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['article-subtitle-1', 'article-text-2', 'article-img-2', 'article-text-3'],
      linkedNodes: {},
      parent: 'article-content-sections',
    },
    'article-subtitle-1': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'La Figura del Lider: Autoridad Moral sin Coerción', fontSize: 24, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-2',
    },
    'article-text-2': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Los líderes tribales (caciques, tusaus, capitanes, headmen) tienen prestigio e influencia pero carecen de poder coercitivo...', fontSize: 16, color: '#ffffff', fontWeight: 'normal' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-2',
    },
    'article-img-2': {
      type: { resolvedName: 'Image' },
      isCanvas: false,
      props: { src: '', alt: 'Segunda imagen del artículo', width: '100%', height: 'auto' },
      displayName: 'Image',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-2',
    },
    'article-text-3': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Continuación del contenido. Detalles sobre las características del liderazgo...', fontSize: 16, color: '#ffffff', fontWeight: 'normal' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-2',
    },
    // Sección 3: Más contenido
    'article-section-3': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['article-subtitle-2', 'article-text-4', 'article-img-3', 'article-text-5'],
      linkedNodes: {},
      parent: 'article-content-sections',
    },
    'article-subtitle-2': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'La Unidad Doméstica y el Parentesco', fontSize: 24, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-3',
    },
    'article-text-4': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'La estructura social se basa en la familia extendida y la comunidad residencial...', fontSize: 16, color: '#ffffff', fontWeight: 'normal' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-3',
    },
    'article-img-3': {
      type: { resolvedName: 'Image' },
      isCanvas: false,
      props: { src: '', alt: 'Tercera imagen del artículo', width: '100%', height: 'auto' },
      displayName: 'Image',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-3',
    },
    'article-text-5': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Más detalles sobre la organización familiar y las alianzas matrimoniales...', fontSize: 16, color: '#ffffff', fontWeight: 'normal' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'article-section-3',
    },
  },
};

// ============================================================================
// PLANTILLA 6: PÁGINA DE FOROS (Lista de categorías)
// Basada en la imagen de la página "Foros" con lista de categorías
// ============================================================================
export const forumCategoriesTemplate = {
  id: 'forum-categories',
  name: 'Foros - Lista de Categorías',
  description: 'Página de listado de categorías del foro con imágenes y contador de temas',
  category: 'Foro',
  preview: '/templates/forum-categories-preview.png',
  template: {
    ROOT: {
      type: { resolvedName: 'BackgroundImageContainer' },
      isCanvas: true,
      props: { padding: 0, background: '#000000' },
      displayName: 'BackgroundImageContainer',
      custom: {},
      hidden: false,
      nodes: ['forums-header', 'forums-main'],
      linkedNodes: {},
    },
    'forums-header': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 16, margin: 0, layout: 'flex', direction: 'row', justify: 'space-between', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['forums-navbar'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'forums-navbar': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#ffffff', padding: 16, margin: 0, layout: 'flex', direction: 'row', justify: 'space-between', align: 'center' },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['forums-logo', 'forums-nav-links'],
      linkedNodes: {},
      parent: 'forums-header',
    },
    'forums-logo': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Akaru', fontSize: 24, fontWeight: 'bold', color: '#000000' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forums-navbar',
    },
    'forums-nav-links': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Flora | Tribus | Fauna | Usos | Agua | Cultura | Geografia | Inicio', fontSize: 14, color: '#000000' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forums-navbar',
    },
    'forums-main': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: '#000000', padding: 48, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'flex-start', gap: 24 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: ['forums-title', 'forums-categories-list'],
      linkedNodes: {},
      parent: 'ROOT',
    },
    'forums-title': {
      type: { resolvedName: 'Text' },
      isCanvas: false,
      props: { text: 'Foros', fontSize: 48, fontWeight: 'bold', color: '#ffffff' },
      displayName: 'Text',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forums-main',
    },
    'forums-categories-list': {
      type: { resolvedName: 'Container' },
      isCanvas: false,
      props: { background: 'transparent', padding: 0, margin: 0, layout: 'flex', direction: 'column', justify: 'flex-start', align: 'stretch', gap: 16 },
      displayName: 'Container',
      custom: {},
      hidden: false,
      nodes: [],
      linkedNodes: {},
      parent: 'forums-main',
    },
  },
};

// Array con todas las plantillas disponibles
export const allTemplates = [
  homepageTemplate,
  blogPostTemplate,
  categoryPageTemplate,
  forumPageTemplate,
  detailedArticleTemplate,
  forumCategoriesTemplate,
];

// Función helper para obtener una plantilla por ID
export function getTemplate(templateId) {
  return allTemplates.find(t => t.id === templateId) || null;
}

// Función helper para obtener plantillas por categoría
export function getTemplatesByCategory(category) {
  return allTemplates.filter(t => t.category === category);
}

// Función helper para obtener todas las categorías disponibles
export function getTemplateCategories() {
  const categories = new Set(allTemplates.map(t => t.category));
  return Array.from(categories);
}
